const teamOf23 = {
  year: "2023",
  presidents: [
    {
      name: "Rushil BR",
      post: "President",
      instagram: "rushil_br",
      linkedin: "rushil_br",
      email: "rushil_br",
      github: "rushil-br",
      imageUrl: "",
    },
    {
      name: "Rushil BR",
      post: "Vice President",
      instagram: "rushil_br",
      linkedin: "rushil_br",
      email: "rushil_br",
      github: "hi-kartik2004",
      imageUrl: "",
    },
  ],
  publicRelationsTeam: [
    {
      name: "Rushil BR",
      post: "Lead",
      instagram: "",
      linkedin: "",
      github: "",
      email: "",
      github: "hi-kartik2004",
      imageUrl: "",
    },
    {
      name: "Rushil BR",
      post: "Vice Lead",
      instagram: "",
      linkedin: "",
      email: "",
      github: "hi-kartik2004",
      imageUrl: "",
    },
    {
      name: "Rushil BR",
      post: "Executive",
      instagram: "",
      linkedin: "",
      email: "",
      github: "hi-kartik2004",
    },
  ],
  designTeam: [
    {
      name: "Rushil BR",
      post: "Lead",
      instagram: "",
      linkedin: "",
      email: "",
    },
    {
      name: "Rushil BR",
      post: "Vice Lead",
      instagram: "",
      linkedin: "",
      email: "",
    },
    {
      name: "Rushil BR",
      post: "Executive",
      instagram: "",
      linkedin: "",
      email: "",
    },
  ],
  technicalTeam: [
    {
      name: "Rushil BR",
      post: "Lead",
      instagram: "",
      linkedin: "",
      email: "",
    },
    {
      name: "Rushil BR",
      post: "Vice Lead",
      instagram: "",
      linkedin: "",
      email: "",
    },
    {
      name: "Rushil BR",
      post: "Executive",
      instagram: "",
      linkedin: "",
      email: "",
    },
  ],
  marketingTeam: [
    {
      name: "Rushil BR",
      post: "Lead",
      instagram: "",
      linkedin: "",
      email: "",
    },
    {
      name: "Rushil BR",
      post: "Vice Lead",
      instagram: "",
      linkedin: "",
      email: "",
    },
    {
      name: "Rushil BR",
      post: "Executive",
      instagram: "",
      linkedin: "",
      email: "",
    },
  ],
  contentTeam: [
    {
      name: "Rushil BR",
      post: "Lead",
      instagram: "",
      linkedin: "",
      email: "",
    },
    {
      name: "Rushil BR",
      post: "Vice Lead",
      instagram: "",
      linkedin: "",
      email: "",
    },
    {
      name: "Rushil BR",
      post: "Executive",
      instagram: "",
      linkedin: "",
      email: "",
    },
  ],
  operationsTeam: [
    {
      name: "Rushil BR",
      post: "Lead",
      instagram: "",
      linkedin: "",
      email: "",
    },
    {
      name: "Rushil BR",
      post: "Vice Lead",
      instagram: "",
      linkedin: "",
      email: "",
    },
    {
      name: "Rushil BR",
      post: "Executive",
      instagram: "",
      linkedin: "",
      email: "",
    },
  ],
};

const teamOf24 = {
  year: "2024",
  presidents: [
    {
      name: "Rushil B R",
      post: "President",
      instagram: "hill__rush",
      linkedin: "https://www.linkedin.com/in/rushil-b-r",
      email: "rushilbr225@gmail.com",
      github: "rushilbr225",
      imageUrl: "https://i.postimg.cc/sXnmnz9q/IMG-20231123-WA0057.jpg",
    },
    {
      name: "Srivatsa Sheshadri",
      post: "Vice President",
      instagram: "srivatsashesha",
      linkedin: "https://www.linkedin.com/in/srivatsa-sheshadri",
      email: "srivatsa.shesha@gmail.com",
      github: "srivatsashesha",
      imageUrl: "https://i.postimg.cc/GhkxNcT9/Snapseed.jpg",
    },
  ],
  publicRelationsTeam: [
    {
      name: "G Vaasudeva",
      post: "Lead",
      instagram: "vaasudevagopal",
      linkedin: "Vaasudeva Gopal",
      github: "",
      email: "vaasudeva0223@gmail.com",
      imageUrl: "https://i.postimg.cc/nLR113Rc/1657018991885.jpg",
    },
    {
      name: "Chyavan Rao A S",
      post: "Executive",
      instagram: "chyavan_rao",
      linkedin: "www.linkedin.com/in/chyavanraoas",
      email: "chyavanrao24@gmail.com",
      github: "Chyavanrao7",
      imageUrl: "https://i.postimg.cc/13txRjqy/1703405812532.jpg",
    },
    {
      name: "Kankana Ghosh",
      post: "Executive",
      instagram: "Kankana_09",
      linkedin: "https://www.linkedin.com/in/kankana-ghosh-b7214a2b6/",
      email: "kankanaghosh129@gmail.com",
      github: "",
      imageUrl: "https://i.postimg.cc/3w4p1vVV/IMG-20240328-210043.jpg",
    },
    {
      name: "Karthikey D Kadati",
      post: "Executive",
      instagram: "karthikey_kadati",
      linkedin:
        "https://www.linkedin.com/in/karthikey-kadati-277420279?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      email: "karthikey5438@gmail.com",
      github: "Karthikey1",
      imageUrl: "https://i.postimg.cc/sgyNRVKR/IMG-20240122-171859.jpg",
    },
    {
      name: "Sindhu T S",
      post: "Executive",
      instagram: "",
      linkedin: "https://www.linkedin.com/in/sindhu-t-s-768855259/",
      email: "jaanu12092003@gmail.com",
      github: "",
      imageUrl: "https://i.postimg.cc/qMGQC432/1686930713217.jpg",
    },
  ],
  designTeam: [
    {
      name: "Ashish",
      post: "Lead",
      instagram: "ashish.naidu.37",
      linkedin: "",
      email: "ashish2003naidu@gmail.com",
      imageUrl: "https://postimg.cc/ZBSBDNV5",
    },
    {
      name: "Veeksha S G",
      post: "Vice Lead",
      instagram: "veeksha_sg",
      linkedin: "https://www.linkedin.com/in/veeksha-s-g-0a8a30228/",
      email: "veekshasg6@gmail.com",
      imageUrl: "https://i.postimg.cc/zXTV64hp/IMG-9312.jpg",
    },
    {
      name: "Dhruv Rathi",
      post: "Executive",
      instagram: "iam_dhruvrathi",
      linkedin: "https://www.linkedin.com/in/dhruv-rathi-399378282",
      email: "dhruv2005rathi@gmail.com",
      imageUrl:
        "https://i.postimg.cc/rwzMynnJ/Screenshot-20231221-112724-Photos-01-01.jpg",
    },
    {
      name: "Manvitha M Puthu",
      post: "Executive",
      instagram: "manvitham654",
      linkedin: "https://www.linkedin.com/in/manvitha-m-puthu-02433a261/",
      email: "manvithaputhu123@gmail.com",
      imageUrl: "https://i.postimg.cc/XJRYXbFm/Manvitha-M-Puthu.jpg",
    },
    {
      name: "Samyuktha Pasumarthi",
      post: "Executive",
      instagram: "samyuktha.pasu",
      linkedin: "",
      email: "samyuktha.pasumarthi@gmail.com",
      imageUrl:
        "https://i.postimg.cc/sDyCGHvD/Whats-App-Image-2024-04-01-at-9-42-28-AM.jpg",
    },
    {
      name: "Zahiya Saher",
      post: "Executive",
      instagram: "zy.saher",
      linkedin: "https://www.linkedin.com/in/zahiya-saher-138a4a260/",
      email: "zahiyasaher19@gmail.com",
      imageUrl: "https://i.postimg.cc/yxjfw0sL/1708171162578.jpg",
    },
  ],
  technicalTeam: [
    {
      name: "Kartikeya Saini",
      post: "Lead",
      instagram: "",
      linkedin: "https://linkedin.com/in/kartikeya-saini-65504b240",
      email: "hire.kartikeya@gmail.com",
      github: "hi-kartik2004",
      imageUrl: "https://i.postimg.cc/25XbVMym/temp.jpg",
    },
    {
      name: "Vansh Bharadwaj",
      post: "Lead",
      instagram: "one__shh",
      linkedin: "https://www.linkedin.com/in/vansh-bhardwaj-5977681b1/",
      email: "vanshayushi@gmail.com",
      github: "Bhardwajvansh",
      imageUrl: "https://i.postimg.cc/SxPmBMKQ/1680862132927.jpg",
    },
    {
      name: "Dhruv Rathi",
      post: "Executive",
      instagram: "iam_dhruvrathi",
      linkedin: "https://www.linkedin.com/in/dhruv-rathi-399378282",
      email: "dhruv2005rathi@gmail.com",
      imageUrl:
        "https://i.postimg.cc/rwzMynnJ/Screenshot-20231221-112724-Photos-01-01.jpg",
    },
    {
      name: "Jagruthi Kareholi",
      post: "Executive",
      instagram: "sapien.j_j",
      linkedin:
        "https://www.linkedin.com/in/jagruthi-kareholi-4a4033299?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      email: "jagruthikareholi@gmail.com",
      imageUrl: "https://i.postimg.cc/Yqtfmdrn/IMG-20240328-WA0018.jpg",
    },

    {
      name: "Zahiya Saher",
      post: "Executive",
      instagram: "zy.saher",
      linkedin: "https://www.linkedin.com/in/zahiya-saher-138a4a260/",
      email: "zahiyasaher19@gmail.com",
      imageUrl: "https://i.postimg.cc/yxjfw0sL/1708171162578.jpg",
    },
  ],
  marketingTeam: [
    {
      name: "Shreyash Suryawanshi",
      post: "Lead",
      instagram: "shreyashsuryawanshi",
      linkedin: "Shreyash Suryawanshi",
      email: "shreyashsuryawanshi926@gmail.com",
      imageUrl:
        "https://i.postimg.cc/XJZMLx5c/22738544-2bc7-4fde-9431-e76cbc2fd4e0.jpg",
    },
    {
      name: "Tejas R Bhoopalam",
      post: "Vice Lead",
      instagram: "tejasrbhoopalam",
      linkedin: "https://www.linkedin.com/in/tejas-r-bhoopalam",
      email: "tejasraghavendrabhoopalam@gmail.com",
      imageUrl:
        "https://i.postimg.cc/bvTKgV4C/Screenshot-20240328-135557-2.jpg",
    },
    {
      name: "Amith Ravindranath",
      post: "Executive",
      instagram: "xtreeme_amith",
      linkedin: "https://www.linkedin.com/in/amith-r-manu-a45344301/",
      email: "lightningretridition@gmail.com",
      imageUrl: "https://i.postimg.cc/HnNJyMyW/IMG-20240328-WA0013.jpg",
    },
    {
      name: "Yadu Vaibhav",
      post: "Executive",
      instagram: "vaibhzyx",
      linkedin:
        "https://www.linkedin.com/in/yadu-vaibhav-90203025a?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      email: "vaibhavyadu8@gmail.com",
      imageUrl: "https://i.postimg.cc/j2ksRwhh/1688193870389.jpg",
    },

    {
      name: "Charan Sai Teja",
      post: "Executive",
      instagram: "CHARAN_SAI_TEJA_2004",
      linkedin: "",
      email: "Charansaiteja348@gmail.com",
      imageUrl:
        "https://i.postimg.cc/B6qcSxyX/Screenshot-20240328-202501-02-01-01.jpg",
    },
  ],
  contentTeam: [
    {
      name: "Saadhvi V",
      post: "Lead",
      instagram: "saadhvix",
      linkedin: "http://linkedin.com/in/saadhvi-v-0a9b01247",
      email: "saadhvi2003@gmail.com",
      imageUrl: "https://i.postimg.cc/d14vWMY0/IMG-2940.jpg",
    },
    {
      name: "Ashray A",
      post: "Executive",
      Instagram: "ashhray",
      linkedin: "https://linkedin.com/in/ashray24",
      email: "ashraynichinmetlu@gmail.com",
      imageUrl: "https://i.postimg.cc/BQ594L0m/profile.png",
    },
    {
      name: "Skanda Bharadwaj",
      post: "Executive",
      instagram: "ska._.nda",
      linkedin: "https://www.linkedin.com/in/skanda-bharadwaj-35779021b",
      email: "skandabharadwaj11@gmail.com",
      imageUrl: "https://i.postimg.cc/g28wmJWv/image.jpg",
    },
    {
      name: "Varsha Rao",
      post: "Executive",
      instagram: "u.no.varsha",
      linkedin: "https://www.linkedin.com/in/varsha-rao-5407032a5",
      email: "varsharao2005@gmail.com",
      imageUrl: "https://i.postimg.cc/9QsS30QG/1711454345619.jpg",
    },
  ],
  operationsTeam: [
    {
      name: "H H Shamanth",
      post: "Lead",
      instagram: "",
      linkedin:
        "https://www.linkedin.com/in/shamanth-acharya-489a78204?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      email: "shamantacharya67@gmail.com",
      imageUrl: "https://i.postimg.cc/SRrSd88R/Shamanth.jpg",
    },
    {
      name: "Danish Neman Sharief",
      post: "Executive",
      instagram: "danish.shariff_",
      linkedin: "https://www.linkedin.com/in/danish-shariff-b48a3025a",
      email: "danishshariff92@gmail.com",
      imageUrl: "https://i.postimg.cc/YSMFZZDz/1706450777661.jpg",
    },
    {
      name: "Nitish Bhat",
      post: "Executive",
      instagram: "nithishbhat_",
      linkedin:
        "https://www.linkedin.com/in/nithish-bhat-098633265?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      email: "nithishbhat44@gmail.com",
      imageUrl: "https://i.postimg.cc/sxSvHJzh/1708151914527.jpg",
    },
    {
      name: "Sujeth",
      post: "Executive",
      instagram: "sujeth.17",
      linkedin: "https://in.linkedin.com/in/sujeth-a-s-61a403278",
      email: "a.s.sujeth17@gmail.com",
      imageUrl:
        "https://i.postimg.cc/wMWmLwNZ/472985860-IMG-20240122-WA0049.jpg",
    },
    {
      name: "Samarth Sutrave",
      post: "Executive",
      instagram: "s_sutrave28",
      linkedin: "https://www.linkedin.com/in/samarth-sutrave-93864425b",
      email: "samarthsutrave28@gmail.com",
      imageUrl:
        "https://i.postimg.cc/cCSKtg5F/IMG-20240211-182530175-MF-PORTRAIT.jpg",
    },
  ],
};

const teamData = [
  // The latest team information must be above the rest which will set it to default.
  { ...teamOf24 },
  {
    ...teamOf23,
  },
];

export default teamData;
