const teamOf23 = {
  year: "2023",
  presidents: [
    {
      name: "Rushil BR",
      post: "President",
      instagram: "rushil_br",
      linkedin: "rushil_br",
      email: "rushil_br",
      github: "rushil-br",
      imageUrl: "",
    },
    {
      name: "Rushil BR",
      post: "Vice President",
      instagram: "rushil_br",
      linkedin: "rushil_br",
      email: "rushil_br",
      github: "hi-kartik2004",
      imageUrl: "",
    },
  ],
  publicRelationsTeam: [
    {
      name: "Rushil BR",
      post: "Lead",
      instagram: "",
      linkedin: "",
      github: "",
      email: "",
      github: "hi-kartik2004",
      imageUrl: "",
    },
    {
      name: "Rushil BR",
      post: "Vice Lead",
      instagram: "",
      linkedin: "",
      email: "",
      github: "hi-kartik2004",
      imageUrl: "",
    },
    {
      name: "Rushil BR",
      post: "Executive",
      instagram: "",
      linkedin: "",
      email: "",
      github: "hi-kartik2004",
    },
  ],
  designTeam: [
    {
      name: "Rushil BR",
      post: "Lead",
      instagram: "",
      linkedin: "",
      email: "",
    },
    {
      name: "Rushil BR",
      post: "Vice Lead",
      instagram: "",
      linkedin: "",
      email: "",
    },
    {
      name: "Rushil BR",
      post: "Executive",
      instagram: "",
      linkedin: "",
      email: "",
    },
  ],
  technicalTeam: [
    {
      name: "Rushil BR",
      post: "Lead",
      instagram: "",
      linkedin: "",
      email: "",
    },
    {
      name: "Rushil BR",
      post: "Vice Lead",
      instagram: "",
      linkedin: "",
      email: "",
    },
    {
      name: "Rushil BR",
      post: "Executive",
      instagram: "",
      linkedin: "",
      email: "",
    },
  ],
  marketingTeam: [
    {
      name: "Rushil BR",
      post: "Lead",
      instagram: "",
      linkedin: "",
      email: "",
    },
    {
      name: "Rushil BR",
      post: "Vice Lead",
      instagram: "",
      linkedin: "",
      email: "",
    },
    {
      name: "Rushil BR",
      post: "Executive",
      instagram: "",
      linkedin: "",
      email: "",
    },
  ],
  contentTeam: [
    {
      name: "Rushil BR",
      post: "Lead",
      instagram: "",
      linkedin: "",
      email: "",
    },
    {
      name: "Rushil BR",
      post: "Vice Lead",
      instagram: "",
      linkedin: "",
      email: "",
    },
    {
      name: "Rushil BR",
      post: "Executive",
      instagram: "",
      linkedin: "",
      email: "",
    },
  ],
  operationsTeam: [
    {
      name: "Rushil BR",
      post: "Lead",
      instagram: "",
      linkedin: "",
      email: "",
    },
    {
      name: "Rushil BR",
      post: "Vice Lead",
      instagram: "",
      linkedin: "",
      email: "",
    },
    {
      name: "Rushil BR",
      post: "Executive",
      instagram: "",
      linkedin: "",
      email: "",
    },
  ],
};

const teamOf24 = {
  year: "2024",
  presidents: [
    {
      name: "Rushil BR",
      post: "President",
      instagram: "rushil_br",
      linkedin: "rushil_br",
      email: "rushil_br",
      github: "hi-kartik2004",
    },
    {
      name: "Rushil BR",
      post: "Vice President",
      instagram: "rushil_br",
      linkedin: "rushil_br",
      email: "rushil_br",
      github: "hi-kartik2004",
    },
  ],
  publicRelationsTeam: [
    {
      name: "Rushil BR",
      post: "Lead",
      instagram: "",
      linkedin: "",
      github: "",
      email: "",
      github: "hi-kartik2004",
    },
    {
      name: "Rushil BR",
      post: "Vice Lead",
      instagram: "",
      linkedin: "",
      email: "",
      github: "hi-kartik2004",
    },
    {
      name: "Rushil BR",
      post: "Executive",
      instagram: "",
      linkedin: "",
      email: "",
      github: "hi-kartik2004",
    },
  ],
  designTeam: [
    {
      name: "Rushil BR",
      post: "Lead",
      instagram: "",
      linkedin: "",
      email: "",
    },
    {
      name: "Rushil BR",
      post: "Vice Lead",
      instagram: "",
      linkedin: "",
      email: "",
    },
    {
      name: "Rushil BR",
      post: "Executive",
      instagram: "",
      linkedin: "",
      email: "",
    },
  ],
  technicalTeam: [
    {
      name: "Rushil BR",
      post: "Lead",
      instagram: "",
      linkedin: "",
      email: "",
    },
    {
      name: "Rushil BR",
      post: "Vice Lead",
      instagram: "",
      linkedin: "",
      email: "",
    },
    {
      name: "Rushil BR",
      post: "Executive",
      instagram: "",
      linkedin: "",
      email: "",
    },
  ],
  marketingTeam: [
    {
      name: "Rushil BR",
      post: "Lead",
      instagram: "",
      linkedin: "",
      email: "",
    },
    {
      name: "Rushil BR",
      post: "Vice Lead",
      instagram: "",
      linkedin: "",
      email: "",
    },
    {
      name: "Rushil BR",
      post: "Executive",
      instagram: "",
      linkedin: "",
      email: "",
    },
  ],
  contentTeam: [
    {
      name: "Rushil BR",
      post: "Lead",
      instagram: "",
      linkedin: "",
      email: "",
    },
    {
      name: "Rushil BR",
      post: "Vice Lead",
      instagram: "",
      linkedin: "",
      email: "",
    },
    {
      name: "Rushil BR",
      post: "Executive",
      instagram: "",
      linkedin: "",
      email: "",
    },
  ],
  operationsTeam: [
    {
      name: "Rushil BR",
      post: "Lead",
      instagram: "",
      linkedin: "",
      email: "",
    },
    {
      name: "Rushil BR",
      post: "Vice Lead",
      instagram: "",
      linkedin: "",
      email: "",
    },
    {
      name: "Rushil BR",
      post: "Executive",
      instagram: "",
      linkedin: "",
      email: "",
    },
  ],
};

const teamData = [
  // The latest team information must be above the rest which will set it to default.
  { ...teamOf24 },
  {
    ...teamOf23,
  },
];

export default teamData;
